### ISSUE TITLE
Backoffice shows everything as clickable/pointer cursor

### ISSUE THREAD

**Issue by ronaldbarendse** [DigitalMomentum/Umbraco7-Videolizer#10]
The Videolizer plugin adds the following CSS that makes the whole Umbraco backoffice seem clickable:
```css
div[ng-click]{
	cursor:pointer;
}
```

This CSS selector seems to be WAY to generic, it should at least be scooped to the Videolizer editor or otherwise be removed!
